[workspace]
resolver = "2"
members = ["crates/agentic-vision", "crates/agentic-vision-mcp"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/agentic-revolution/agentic-vision"
authors = ["Omoshola Owolabi"]
